param(
    [string]$EntryScript = "bid_pyside6.py",
    [string]$AppName = "BidManager",
    [string]$BuildVersion = "",
    [switch]$Clean
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $EntryScript)) {
    throw "Entry script not found: $EntryScript"
}

if (-not (Get-Command pyinstaller -ErrorAction SilentlyContinue)) {
    python -m pip install pyinstaller
}

if (-not $BuildVersion) {
    $BuildVersion = Get-Date -Format "yyyy.MM.dd.HHmmss"
}
$BuildUtc = (Get-Date).ToUniversalTime().ToString("o")
$versionFile = "app_version.py"
$versionLines = @(
    "# Auto-generated by scripts/build_exe.ps1"
    "APP_VERSION = `"$BuildVersion`""
    "BUILD_UTC = `"$BuildUtc`""
)
$versionWritten = $false
for ($i = 0; $i -lt 5 -and -not $versionWritten; $i++) {
    try {
        $tmpVersion = "$versionFile.tmp"
        $versionLines | Set-Content -Path $tmpVersion -Encoding UTF8
        Move-Item -Path $tmpVersion -Destination $versionFile -Force
        $versionWritten = $true
    }
    catch {
        Start-Sleep -Milliseconds 250
    }
}
if (-not $versionWritten) {
    Write-Warning "Could not update $versionFile (file locked). Continuing with existing version file."
}
Write-Host "Build version: $BuildVersion ($BuildUtc)"

$buildArgs = @(
    "-m", "PyInstaller",
    "--noconfirm",
    "--windowed",
    "--onefile",
    "--name", $AppName,
    "--distpath", "dist",
    "--workpath", "build\pyi",
    "--specpath", "build"
)

if ($Clean) {
    $buildArgs += "--clean"
}

if (Test-Path "assets\app.ico") {
    $buildArgs += @("--icon", "assets\app.ico")
}

$buildArgs += $EntryScript
python @buildArgs
if ($LASTEXITCODE -ne 0) {
    throw "PyInstaller failed with exit code $LASTEXITCODE"
}

if (-not (Test-Path "dist\$AppName.exe")) {
    throw "Build finished but dist\$AppName.exe was not found."
}

Write-Host "Build complete: dist\$AppName.exe"
