param(
    [string]$EntryScript = "bid_pyside6.py",
    [string]$AppName = "BidManager",
    [string]$BuildVersion = "",
    [switch]$Clean
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $EntryScript)) {
    throw "Entry script not found: $EntryScript"
}

if (-not (Get-Command pyinstaller -ErrorAction SilentlyContinue)) {
    python -m pip install pyinstaller
}

if (-not $BuildVersion) {
    $BuildVersion = Get-Date -Format "yyyy.MM.dd.HHmmss"
}
$BuildUtc = (Get-Date).ToUniversalTime().ToString("o")
$versionFile = "app_version.py"
$versionLines = @(
    "# Auto-generated by scripts/build_installer.ps1"
    "APP_VERSION = `"$BuildVersion`""
    "BUILD_UTC = `"$BuildUtc`""
)
$versionWritten = $false
for ($i = 0; $i -lt 5 -and -not $versionWritten; $i++) {
    try {
        $tmpVersion = "$versionFile.tmp"
        $versionLines | Set-Content -Path $tmpVersion -Encoding UTF8
        Move-Item -Path $tmpVersion -Destination $versionFile -Force
        $versionWritten = $true
    }
    catch {
        Start-Sleep -Milliseconds 250
    }
}
if (-not $versionWritten) {
    Write-Warning "Could not update $versionFile (file locked). Continuing with existing version file."
}

Write-Host "Installer build version: $BuildVersion ($BuildUtc)"

$distRoot = Join-Path "dist" ("installer_" + $BuildVersion)
$workPath = "build\pyi_onedir"
$buildArgs = @(
    "-m", "PyInstaller",
    "--noconfirm",
    "--windowed",
    "--onedir",
    "--name", $AppName,
    "--distpath", $distRoot,
    "--workpath", $workPath,
    "--specpath", "build"
)

if ($Clean) {
    $buildArgs += "--clean"
}

if (Test-Path "assets\app.ico") {
    $buildArgs += @("--icon", "assets\app.ico")
}

$buildArgs += $EntryScript
python @buildArgs
if ($LASTEXITCODE -ne 0) {
    throw "PyInstaller failed with exit code $LASTEXITCODE"
}

$appDir = Join-Path $distRoot $AppName
$appExe = Join-Path $appDir "$AppName.exe"
if (-not (Test-Path $appExe)) {
    throw "Onedir build missing EXE: $appExe"
}

$uninstallPs1 = Join-Path $appDir "uninstall.ps1"
$uninstallCmd = Join-Path $appDir "uninstall.cmd"
$ps1Content = @"
$ErrorActionPreference = 'SilentlyContinue'
$AppName = '$AppName'
$AppDir = Split-Path -Parent `$MyInvocation.MyCommand.Path
$Desktop = [Environment]::GetFolderPath('Desktop')
$Programs = Join-Path `$env:APPDATA 'Microsoft\Windows\Start Menu\Programs'
$links = @(
  (Join-Path `$Desktop "`$AppName.lnk"),
  (Join-Path `$Programs "`$AppName.lnk"),
  (Join-Path (Join-Path `$Programs `$AppName) "`$AppName.lnk")
)
foreach (`$lnk in `$links) { if (Test-Path `$lnk) { Remove-Item `$lnk -Force } }
$legacy = Join-Path `$env:LOCALAPPDATA `$AppName
if ((Test-Path `$legacy) -and (`$legacy -ne `$AppDir)) {
  Remove-Item `$legacy -Recurse -Force
}
Start-Sleep -Milliseconds 500
Remove-Item `$AppDir -Recurse -Force
"@
$cmdContent = @"
@echo off
setlocal
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0uninstall.ps1"
echo Uninstall started. You can close this window.
timeout /t 2 /nobreak >nul
"@
$ps1Content | Set-Content -Path $uninstallPs1 -Encoding UTF8
$cmdContent | Set-Content -Path $uninstallCmd -Encoding ASCII

New-Item -ItemType Directory -Force -Path "deploy" | Out-Null

function Resolve-IsccPath {
    $cmd = Get-Command iscc -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    $candidates = @(
        "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
        "${env:ProgramFiles}\Inno Setup 6\ISCC.exe"
    )
    foreach ($p in $candidates) {
        if (Test-Path $p) { return $p }
    }
    return $null
}

$isccPath = Resolve-IsccPath
$setupName = "${AppName}Setup_${BuildVersion}"

if ($isccPath) {
    $installerDir = "build\installer"
    New-Item -ItemType Directory -Force -Path $installerDir | Out-Null
    $issPath = Join-Path $installerDir "${AppName}.iss"
    $srcAbs = (Resolve-Path $appDir).Path
    $outAbs = (Resolve-Path "deploy").Path
    $iconLine = ""
    if (Test-Path "assets\app.ico") {
        $iconAbs = (Resolve-Path "assets\app.ico").Path
        $iconLine = "SetupIconFile=$iconAbs"
    }
    $issContent = @"
[Setup]
AppId={{A1BC5A89-1FAD-4F6D-9146-3E2E8C1670DF}
AppName=$AppName
AppVersion=$BuildVersion
AppPublisher=BidManager
DefaultDirName={localappdata}\$AppName
DefaultGroupName=$AppName
DisableProgramGroupPage=yes
OutputDir=$outAbs
OutputBaseFilename=$setupName
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
$iconLine

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional icons:"; Flags: unchecked

[Files]
Source: "$srcAbs\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{autoprograms}\$AppName"; Filename: "{app}\$AppName.exe"
Name: "{autodesktop}\$AppName"; Filename: "{app}\$AppName.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\$AppName.exe"; Description: "Launch $AppName"; Flags: nowait postinstall skipifsilent
"@
    $issContent | Set-Content -Path $issPath -Encoding UTF8

    & $isccPath $issPath
    if ($LASTEXITCODE -ne 0) {
        throw "Inno Setup compile failed with exit code $LASTEXITCODE"
    }
    Write-Host "Installer created in deploy: $setupName.exe"
}
else {
    $zipPath = Join-Path "deploy" "${AppName}_portable_${BuildVersion}.zip"
    $zipped = $false
    for ($i = 0; $i -lt 5 -and -not $zipped; $i++) {
        try {
            if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
            Compress-Archive -Path (Join-Path $appDir "*") -DestinationPath $zipPath -CompressionLevel Optimal
            $zipped = $true
        }
        catch {
            Start-Sleep -Milliseconds 500
        }
    }
    if ($zipped) {
        Write-Warning "Inno Setup not found. Created portable package instead: $zipPath"
    }
    else {
        Write-Warning "Inno Setup not found and ZIP packaging was blocked by file locks. Use onedir output: $appDir"
    }
}

$manifest = [ordered]@{
    app_name = $AppName
    build_type = "installer_onedir"
    version = $BuildVersion
    built_at_utc = $BuildUtc
    app_dir = $appDir
}
$manifestPath = Join-Path "deploy" "build_version_installer.json"
$manifest | ConvertTo-Json | Set-Content -Path $manifestPath -Encoding UTF8
Write-Host "Installer manifest written: $manifestPath"
